**The Scenario:** You act as a university data analyst. The legacy admissions portal crashed during a system migration, and the backup applicant data is a mess. You must clean the "Applicant Records" dataset.
- Handling Missing Data: The dataset is riddled with NaNs. You must use .dropna() to remove rows completely missing an Application ID. You will use .fillna() to replace missing Intended Major and High School State values with "Unknown" that were lost during the export.
- Handling Duplicates: A server glitch caused applicants to accidentally submit identical applications twice. You must use .duplicated() to find identical application rows and .drop_duplicates(keep='first') to remove the errors and keep only the original submission.

In [16]:
import pandas as pd

df = pd.read_csv("admissions_messy.csv")
df.info()
df.head()

df = df.dropna(subset=["Application ID"])

df["Intended Major"] = df["Intended Major"].fillna("Unknown")
df["High School State"] = df["High School State"].fillna("Unknown")
# print(df)
duplicates = df[df.duplicated()]
print(f"Duplicate rows:\n {duplicates}")

df = df.drop_duplicates(keep="first")
df.info()
df.head()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Application ID     943 non-null    float64
 1   Applicant Name     1050 non-null   object
 2   Email              1050 non-null   object
 3   Intended Major     898 non-null    object
 4   High School State  874 non-null    object
 5   Application Fee    1050 non-null   object
 6   Submission Date    1050 non-null   object
dtypes: float64(1), object(6)
memory usage: 57.6+ KB
Duplicate rows:
       Application ID       Applicant Name                  Email  \
77            1210.0        Bruce Allen        ballen@skynet.com
144           1986.0          ALICE Doe           adoe@stark.com
147           1319.0         peter DOE              pdoe@edu.org
160           1513.0           ARTHUR Doe         adoe@gmail.com
177           1059.0      Victor CONNOR        vconnor@stark.com
183           1136.0         Clark PRINCE      cprince@gmail.com
211           1636.0         BOB Smith          bsmith@stark.com
301           1439.0          SARA PRINCE      sprince@yahoo.com
348           1626.0        VICTOR JONES       vjones@skynet.com
365           1096.0       ALICE BROWN          abrown@stark.com
414           1811.0         Diana Jones      djones@outlook.com
437           1902.0           John JANE       jjane@outlook.com
451           1737.0       Bruce curry          bcurry@gmail.com
461           1601.0        hal PARKER         hparker@gmail.com
478           1549.0          mary brown        mbrown@gmail.com
480           1837.0          DIANA KENT         dkent@stark.com
482           1174.0       Alice connor        aconnor@stark.com
519           1761.0          BARRY STONE       bstone@yahoo.com
536           1660.0         Mary wayne    mwayne@dailybugle.com
547           1346.0         SARA jane         sjane@outlook.com
553           1678.0           Victor DOE    vdoe@dailybugle.com
559           1521.0        ARTHUR ALLEN        aallen@gmail.com
654           1499.0      VICTOR Prince        vprince@gmail.com
689           1371.0     ARTHUR ROGERS       arogers@outlook.com
697           1198.0        CHARLIE Jane         cjane@stark.com
706           1687.0       CLARK PRINCE       cprince@skynet.com
720           1883.0       bruce brown        bbrown@outlook.com
726           1076.0       Wanda Allen          wallen@stark.com
732           1280.0       clark stone        cstone@outlook.com
764           1740.0        diana Allen           dallen@edu.org
777           1947.0       Sara PRINCE           sprince@edu.org
812           1901.0       arthur BROWN         abrown@yahoo.com
829           1938.0           arthur Doe         adoe@gmail.com
846           1101.0       CHARLIE STONE      cstone@outlook.com
852           1277.0        WANDA STONE           wstone@edu.org
855           1973.0           sara jane         sjane@stark.com
878           1899.0         PETER rogers      progers@gmail.com
941           1139.0      ALICE Connor         aconnor@gmail.com
970           1527.0         hal Wayne          hwayne@stark.com
984           1859.0       CHARLIE CURRY   ccurry@dailybugle.com
985           1974.0        WANDA JONES        wjones@skynet.com
996           1584.0          PETER DOE      pdoe@dailybugle.com
1016          1312.0    charlie Jordan         cjordan@gmail.com
1023          1235.0       ALICE BROWN          abrown@stark.com
1048          1299.0          peter Wayne  pwayne@dailybugle.com

        Intended Major High School State Application Fee Submission Date
77    Computer Science                AZ       $1,160.63      08-30-2023
144        Engineering                NV         $786.35      2023-04-11
147            Unknown                FL          $22.59      2023-05-25
160            Biology                CA         $193.68      01/04/2023
177        Agriculture                NJ       $1,493.12      02/28/2023
183            History                NV         $504.84         unknown
211            Biology                KS         $215.32      2023/03/10
301         Journalism                NY       $1,697.19      08-01-2023
348            Physics                AZ       $1,755.61      2023-07-21
365            Unknown           Unknown         $733.90      2023-05-23
414            History                NV       $1,808.56      2023/06/13
437               Math                WA      $1,779.17       2023/11/10
451               Math                TX        $357.59       12/11/2023
461                Art                FL       $1,907.52      08/17/2023
478           Business                NJ      $1,400.32       04/24/2023
480         Journalism                NJ         $785.26         pending
482         Journalism           Unknown         $913.49    May 30, 2023
519   Computer Science           Unknown       $1,425.39      06/27/2023
536            History                WA        $459.53       2023/03/06
547         Journalism                NY         $554.57      07/18/2023
553           Business                AZ      $1,718.61     Aug 06, 2023
559               Math                KS        $289.40       04/23/2023
654           Business                TX         $664.09      12/19/2023
689        Engineering                NJ         $453.56      05-28-2023
697            Biology                WA        $403.84       03-17-2023
706        Engineering                FL         $154.95      2023-04-21
720        Agriculture           Unknown       $1,919.24      03-16-2023
726         Journalism                TX         $152.76    Sep 29, 2023
732        Agriculture                CA        $304.30       2023-01-12
764           Business           Unknown       $1,879.97      07/29/2023
777        Engineering                NV      $1,151.42       2023/09/16
812           Business           Unknown          $18.45      06-25-2023
829                Art           Unknown       $1,375.91      02/20/2023
846         Journalism                FL        $692.05       05-26-2023
852   Computer Science                KS         $824.41         pending
855         Journalism           Unknown         $991.50      06/26/2023
878            Unknown                NJ        $779.12     Aug 26, 2023
941                Art                WA       $1,354.07      07-16-2023
970   Computer Science                WA         $550.43         pending
984        Agriculture                TX         $775.72      10-05-2023
985            Unknown                AZ         $646.05      2023-07-22
996            Physics           Unknown         $810.14      12/31/2023
1016           Physics                NY        $182.38       11/21/2023
1023        Journalism           Unknown       $1,415.36    Apr 05, 2023
1048        Journalism                KS         $689.05      2023-06-06
<class 'pandas.core.frame.DataFrame'>
Index: 898 entries, 0 to 1047
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Application ID     898 non-null    float64
 1   Applicant Name     898 non-null    object
 2   Email              898 non-null    object
 3   Intended Major     898 non-null    object
 4   High School State  898 non-null    object
 5   Application Fee    898 non-null    object
 6   Submission Date    898 non-null    object
dtypes: float64(1), object(6)
memory usage: 56.1+ KB

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,$297.91,pending
1,1689.0,PETER JONES,pjones@edu.org,Journalism,Unknown,"$1,939.68",08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,Unknown,$277.90,2023/06/06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,$370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,$53.93,"Oct 16, 2023"
...,...,...,...,...,...,...,...
1043,1871.0,Arthur Wayne,awayne@gmail.com,Art,NJ,"$1,619.10",05-07-2023
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,"$1,582.76",2023/05/27
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,Unknown,AZ,$862.30,10-18-2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,Unknown,$389.22,10-20-2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,"$1,746.27","Aug 17, 2023"

**Data Type Conversions:** 
- Application Fee is imported as a string (e.g., "$150.50"). You must remove the symbols and use pd.to_numeric() to turn it into a float.
- Replace “pending” and “unknown” text entries in the dates with the previous valid datetime (forward filling).
- Convert Submission Date from messy text into a proper datetime object using pd.to_datetime().
- Convert the Submission Date format from various mixed formats into a uniform "M/D/Y" format.

In [19]:
df["Application Fee"] = (df["Application Fee"].replace(r"[\$,]", "", regex=True))
df["Application Fee"] = pd.to_numeric(df["Application Fee"], errors="coerce")

df["Submission Date"] = df["Submission Date"].replace(["pending", "unknown"], pd.NA)
df["Submission Date"] = df["Submission Date"].fillna(method="ffill")

df["Submission Date"] = pd.to_datetime(df["Submission Date"], errors="coerce")

# df["Submission Date"] = df["Submission Date"].dt.strftime("%-m/%-d/%Y")
df["Submission Date"] = df["Submission Date"].dt.strftime("%m/%d/%Y")

print(df[["Application Fee", "Submission Date"]].head())
df.info()

   Application Fee Submission Date
0           297.91             NaN
1          1939.68      08/14/2023
2           277.90      08/14/2023
3           370.25      08/14/2023
4            53.93      08/14/2023
<class 'pandas.core.frame.DataFrame'>
Index: 898 entries, 0 to 1047
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Application ID     898 non-null    float64
 1   Applicant Name     898 non-null    object
 2   Email              898 non-null    object
 3   Intended Major     898 non-null    object
 4   High School State  898 non-null    object
 5   Application Fee    898 non-null    float64
 6   Submission Date    897 non-null    object
dtypes: float64(2), object(5)
memory usage: 56.1+ KB

C:\Users\Dell\AppData\Local\Temp\ipykernel_15440\1546740097.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Submission Date"] = df["Submission Date"].fillna(method="ffill")

 **String Manipulation:** The Applicant Name column has chaotic capitalization and extra spaces. You will use .str.title() and .str.strip() to fix this. You must also extract the email domain (e.g., extracting "yahoo.com" from "student@yahoo.com") using .str.split() to see which email providers are most common.

In [12]:
df["Applicant Name"] = (df["Applicant Name"].str.strip().str.title())
df["Applicant Name"] = (df["Applicant Name"].str.strip().str.replace(r"\s+", " ", regex=True).str.title())
print(df["Applicant Name"])

df["Email Domain"] = df["Email"].str.split("@").str[-1]
domain_counts = df["Email Domain"].value_counts()

print(domain_counts.head())

top_provider = df["Email Domain"].mode()[0]
print("Most common email provider:", top_provider)

df.to_csv("cleaned_applicant_records.csv", index=False)

0            Wanda Doe
1          Peter Jones
2       Wanda Maximoff
3         Peter Parker
4         Bruce Rogers
             ...
1045    Diana Maximoff
1046       Steve Allen
1047    Charlie Rogers
1048       Peter Wayne
1049     Charlie Brown
Name: Applicant Name, Length: 1050, dtype: object
Email Domain
gmail.com         167
stark.com         162
yahoo.com         150
dailybugle.com    147
edu.org           145
Name: count, dtype: int64
Most common email provider: gmail.com

In [9]:
df = pd.read_csv("admissions_messy.csv")
df

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,$297.91,pending
1,1689.0,PETER JONES,pjones@edu.org,Journalism,NaN,"$1,939.68",08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,NaN,$277.90,2023/06/06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,$370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,$53.93,"Oct 16, 2023"
...,...,...,...,...,...,...,...
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,NaN,AZ,$862.30,10-18-2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,NaN,$389.22,10-20-2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,"$1,746.27","Aug 17, 2023"
1048,1299.0,peter Wayne,pwayne@dailybugle.com,Journalism,KS,$689.05,2023-06-06
1049,NaN,CHARLIE Brown,cbrown@yahoo.com,Business,KS,"$1,875.22",unknown